import {
  docsBatchSchema,
  docsBookmarkCreateSchema,
  docsBookmarkDeleteSchema,
  docsBookmarksListSchema,
  docsCreateDocumentSchema,
  docsDeleteParagraphSchema,
  docsDocumentGetSchema,
  docsFormatTextSchema,
  docsGetAsJsonSchema,
  docsHeaderFooterSchema,
  docsInsertHorizontalRuleSchema,
  docsInsertImageSchema,
  docsInsertListSchema,
  docsInsertPageBreakSchema,
  docsInsertParagraphSchema,
  docsInsertTableSchema,
  docsNamedRangeCreateSchema,
  docsNamedRangeDeleteSchema,
  docsNamedRangesListSchema,
  docsPageSetupGetSchema,
  docsPageSetupUpdateSchema,
  docsReplaceTextSchema,
  docsSetTextSchema,
  docsTableOfContentsListSchema,
  docsUpdateParagraphSchema,
} from '../../schemas.js'
import type { ToolSpec } from '../types.js'

/** docs service catalog — 26 tools. */
export const docsTools: ToolSpec[] = [
  {
    name: 'docs_batch',
    service: 'docs',
    action: 'batch',
    description: "Execute multiple operations in a single round-trip against one existing document. Pass an ordered array of {action, params} objects. Actions are the same names used by individual tools (documentGet, documentGetJson, paragraphInsert, paragraphUpdate, paragraphDelete, setText, replaceText, listInsert, tableInsert, imageInsert, pageBreakInsert, horizontalRuleInsert, formatText, headerSet, footerSet, pageSetupGet, pageSetupUpdate, bookmarksList, bookmarkCreate, bookmarkDelete, namedRangesList, namedRangeCreate, namedRangeDelete, tableOfContentsList). Operations execute sequentially; errors are collected per-operation with partial-success metadata. Requires documentId.",
    schema: docsBatchSchema,
    batchEligible: false,
    isBatchTool: true,
    cli: { paramsJsonOnly: true },
    group: 'batch',
    formatter: { kind: 'text' },
  },
  {
    name: 'docs_create_bookmark',
    service: 'docs',
    action: 'bookmarkCreate',
    description: "Create a bookmark at a paragraph character offset.",
    schema: docsBookmarkCreateSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Bookmark created." },
  },
  {
    name: 'docs_create_document',
    service: 'docs',
    action: 'documentCreate',
    description: "Create a new Google Docs document.",
    schema: docsCreateDocumentSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Document created." },
  },
  {
    name: 'docs_create_named_range',
    service: 'docs',
    action: 'namedRangeCreate',
    description: "Create a named range around a paragraph or a partial paragraph text span.",
    schema: docsNamedRangeCreateSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Named range created." },
  },
  {
    name: 'docs_delete_bookmark',
    service: 'docs',
    action: 'bookmarkDelete',
    description: "Delete a bookmark by ID. Requires confirm=true.",
    schema: docsBookmarkDeleteSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Bookmark deleted." },
  },
  {
    name: 'docs_delete_named_range',
    service: 'docs',
    action: 'namedRangeDelete',
    description: "Delete a named range by ID. Requires confirm=true.",
    schema: docsNamedRangeDeleteSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Named range deleted." },
  },
  {
    name: 'docs_delete_paragraph',
    service: 'docs',
    action: 'paragraphDelete',
    description: "Delete a paragraph by index from a document.",
    schema: docsDeleteParagraphSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Paragraph deleted." },
  },
  {
    name: 'docs_format_text',
    service: 'docs',
    action: 'formatText',
    description: "Format text in the document by search pattern. Finds the text and applies formatting: bold, italic, underline, strikethrough, font family, font size, colors, or links.",
    schema: docsFormatTextSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text' },
  },
  {
    name: 'docs_get_as_json',
    service: 'docs',
    action: 'documentGetJson',
    description: "Get the full document as structured JSON via the Docs Advanced Service. Returns the complete document tree with all content, formatting, and structure. This is an alternative to the paragraph-based docs_get_document.",
    schema: docsGetAsJsonSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Document JSON retrieved." },
  },
  {
    name: 'docs_get_document',
    service: 'docs',
    action: 'documentGet',
    description: "Get document metadata including ID, name, URL, and full text content with paragraph breakdown.",
    schema: docsDocumentGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Document retrieved." },
  },
  {
    name: 'docs_get_page_setup',
    service: 'docs',
    action: 'pageSetupGet',
    description: "Read page size and margin settings from a Google Docs document. Values are returned in points.",
    schema: docsPageSetupGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Page setup retrieved." },
  },
  {
    name: 'docs_insert_horizontal_rule',
    service: 'docs',
    action: 'horizontalRuleInsert',
    description: "Insert a horizontal rule divider into the document.",
    schema: docsInsertHorizontalRuleSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Horizontal rule inserted." },
  },
  {
    name: 'docs_insert_image',
    service: 'docs',
    action: 'imageInsert',
    description: "Insert an image from a public URL into the document.",
    schema: docsInsertImageSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Image inserted." },
  },
  {
    name: 'docs_insert_list',
    service: 'docs',
    action: 'listInsert',
    description: "Insert a bulleted or numbered list into the document.",
    schema: docsInsertListSchema,
    batchEligible: true,
    group: 'list',
    formatter: { kind: 'text', summary: "List inserted." },
  },
  {
    name: 'docs_insert_page_break',
    service: 'docs',
    action: 'pageBreakInsert',
    description: "Insert a page break into the document.",
    schema: docsInsertPageBreakSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Page break inserted." },
  },
  {
    name: 'docs_insert_paragraph',
    service: 'docs',
    action: 'paragraphInsert',
    description: "Insert a paragraph into a document. Optionally set text, heading level (HEADING1-6 or NORMAL), and position (append or prepend).",
    schema: docsInsertParagraphSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Paragraph inserted." },
  },
  {
    name: 'docs_insert_table',
    service: 'docs',
    action: 'tableInsert',
    description: "Insert a table into the document from a 2D array of values. First row is treated as header and bolded.",
    schema: docsInsertTableSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Table inserted." },
  },
  {
    name: 'docs_list_bookmarks',
    service: 'docs',
    action: 'bookmarksList',
    description: "List document bookmarks with IDs and resolved paragraph positions where available.",
    schema: docsBookmarksListSchema,
    batchEligible: true,
    group: 'list',
    formatter: { kind: 'text', summary: "Bookmarks listed." },
  },
  {
    name: 'docs_list_named_ranges',
    service: 'docs',
    action: 'namedRangesList',
    description: "List document named ranges, optionally filtered by name.",
    schema: docsNamedRangesListSchema,
    batchEligible: true,
    group: 'list',
    formatter: { kind: 'text', summary: "Named ranges listed." },
  },
  {
    name: 'docs_list_table_of_contents',
    service: 'docs',
    action: 'tableOfContentsList',
    description: "List existing Google Docs table-of-contents elements with child indexes and text previews.",
    schema: docsTableOfContentsListSchema,
    batchEligible: true,
    group: 'list',
    formatter: { kind: 'text', summary: "Tables of contents listed." },
  },
  {
    name: 'docs_replace_text',
    service: 'docs',
    action: 'replaceText',
    description: "Find and replace text across the entire document.",
    schema: docsReplaceTextSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Text replaced." },
  },
  {
    name: 'docs_set_footer',
    service: 'docs',
    action: 'footerSet',
    description: "Set the document footer text. Use empty string to clear.",
    schema: docsHeaderFooterSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Footer set." },
  },
  {
    name: 'docs_set_header',
    service: 'docs',
    action: 'headerSet',
    description: "Set the document header text. Use empty string to clear.",
    schema: docsHeaderFooterSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Header set." },
  },
  {
    name: 'docs_set_text',
    service: 'docs',
    action: 'setText',
    description: "Replace the entire document body with new text.",
    schema: docsSetTextSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Document text set." },
  },
  {
    name: 'docs_update_page_setup',
    service: 'docs',
    action: 'pageSetupUpdate',
    description: "Update page size and margins for a Google Docs document. Values are points.",
    schema: docsPageSetupUpdateSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Page setup updated." },
  },
  {
    name: 'docs_update_paragraph',
    service: 'docs',
    action: 'paragraphUpdate',
    description: "Update heading level and/or text of an existing paragraph by index.",
    schema: docsUpdateParagraphSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Paragraph updated." },
  },
]
