import { formatList } from '../../response.js'
import {
  driveAddParentSchema,
  driveBatchSchema,
  driveChangesListSchema,
  driveChangesStartPageTokenSchema,
  driveCommentCreateSchema,
  driveCommentDeleteSchema,
  driveCommentGetSchema,
  driveCommentUpdateSchema,
  driveCommentsListSchema,
  driveExportAsSchema,
  driveFolderPathSchema,
  driveRemoveParentSchema,
  driveRepliesListSchema,
  driveReplyCreateSchema,
  driveReplyDeleteSchema,
  driveReplyGetSchema,
  driveReplyUpdateSchema,
  driveRevisionGetSchema,
  driveRevisionUpdateSchema,
  driveRevisionsListSchema,
  driveSharedDriveGetSchema,
  driveSharedDrivesListSchema,
  fileAddEditorSchema,
  fileAddViewerSchema,
  fileCopySchema,
  fileCreateSchema,
  fileExportSchema,
  fileGetSchema,
  fileListSchema,
  fileMoveSchema,
  fileRemoveEditorSchema,
  fileRemoveViewerSchema,
  fileSearchSchema,
  fileSetSharingSchema,
  fileTrashSchema,
  fileUntrashSchema,
  fileUpdateContentSchema,
  fileUpdateMetaSchema,
  folderCreateSchema,
  folderGetSchema,
  folderListSchema,
} from '../../schemas.js'
import type { ToolSpec } from '../types.js'

/** drive service catalog — 44 tools. */
export const driveTools: ToolSpec[] = [
  {
    name: 'drive_about',
    service: 'drive',
    action: 'about',
    description: "Get Drive storage information including total storage, used storage, and root folder ID.",
    schema: {},
    batchEligible: true,
    group: 'read',
    formatter: {
      kind: 'list',
      formatMcp: (result) => formatList(result, {
        itemsKey: 'items',
        noun: 'file',
        itemSummary: (item: unknown) => {
          const r = item as Record<string, unknown>
          return String(r.title ?? r.name ?? r.id ?? r.summary ?? JSON.stringify(r).slice(0, 120))
        },
      }),
    },
  },
  {
    name: 'drive_add_comment',
    service: 'drive',
    action: 'commentCreate',
    description: "Add a comment to a Drive file. The comment is head-anchored (appears at the top of the file).",
    schema: driveCommentCreateSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Comment added successfully." },
  },
  {
    name: 'drive_add_editor',
    service: 'drive',
    action: 'fileAddEditor',
    description: "Add an editor to a file by email address.",
    schema: fileAddEditorSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Editor added successfully." },
  },
  {
    name: 'drive_add_parent',
    service: 'drive',
    action: 'fileAddParent',
    description: "Add a file to an additional parent folder without removing existing parents.",
    schema: driveAddParentSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "File added to folder." },
  },
  {
    name: 'drive_add_viewer',
    service: 'drive',
    action: 'fileAddViewer',
    description: "Add a viewer to a file by email address.",
    schema: fileAddViewerSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Viewer added successfully." },
  },
  {
    name: 'drive_batch',
    service: 'drive',
    action: 'batch',
    description: "Execute multiple Drive operations in a single round-trip. Pass an ordered array of {action, params} objects. Actions are the same names used by individual tools (about, fileGet, fileList, fileSearch, fileExport, folderGet, folderList, folderListRoot, folderCreate, fileCreate, fileCopy, fileMove, fileUpdateMeta, fileUpdateContent, fileGetPermissions, fileSetSharing, fileAddEditor, fileAddViewer, fileRemoveEditor, fileRemoveViewer, fileAddParent, fileRemoveParent, folderPath, fileTrash, fileUntrash, fileDelete, fileExportAs, commentsList, commentsGet, commentCreate, commentsUpdate, commentsDelete, repliesList, repliesCreate, repliesGet, repliesUpdate, repliesDelete, revisionsList, revisionsGet, revisionsUpdate, sharedDrivesList, sharedDrivesGet, changesStartPageToken, changesList). Operations execute sequentially; errors are collected per-operation. Up to 20 operations.",
    schema: driveBatchSchema,
    batchEligible: false,
    isBatchTool: true,
    cli: { paramsJsonOnly: true },
    group: 'batch',
    formatter: {
      kind: 'list',
      formatMcp: (result) => formatList(result, {
        itemsKey: 'items',
        noun: 'item',
        itemSummary: (item: unknown) => {
          const r = item as Record<string, unknown>
          return String(r.title ?? r.name ?? r.id ?? r.summary ?? JSON.stringify(r).slice(0, 120))
        },
      }),
    },
  },
  {
    name: 'drive_copy_file',
    service: 'drive',
    action: 'fileCopy',
    description: "Copy a Drive file. Optionally rename and/or move to a different folder.",
    schema: fileCopySchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "File copied successfully." },
  },
  {
    name: 'drive_create_file',
    service: 'drive',
    action: 'fileCreate',
    description: "Create a new file in Drive with content. Specify mimeType for non-text files (e.g. text/markdown, application/json).",
    schema: fileCreateSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "File created successfully." },
  },
  {
    name: 'drive_create_folder',
    service: 'drive',
    action: 'folderCreate',
    description: "Create a new folder in Drive. Optionally specify a parent folder ID.",
    schema: folderCreateSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Folder created successfully." },
  },
  {
    name: 'drive_create_reply',
    service: 'drive',
    action: 'repliesCreate',
    description: "Create a reply on a Drive file comment.",
    schema: driveReplyCreateSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Reply created successfully." },
  },
  {
    name: 'drive_delete_comment',
    service: 'drive',
    action: 'commentsDelete',
    description: "Delete a Drive file comment. Requires explicit confirmation.",
    schema: driveCommentDeleteSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Comment deleted successfully." },
  },
  {
    name: 'drive_delete_file',
    service: 'drive',
    action: 'fileDelete',
    description: "Move a file to trash through the delete workflow. Permanent deletion requires emptying trash in Drive.",
    schema: fileGetSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "File deleted (moved to trash)." },
  },
  {
    name: 'drive_delete_reply',
    service: 'drive',
    action: 'repliesDelete',
    description: "Delete a Drive file comment reply. Requires explicit confirmation.",
    schema: driveReplyDeleteSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Reply deleted successfully." },
  },
  {
    name: 'drive_export_as',
    service: 'drive',
    action: 'fileExportAs',
    description: "Export a Google Workspace file (Docs, Sheets, Slides) in a format like PDF, DOCX, XLSX, CSV. Returns a base64-encoded blob. Use drive_read_file for plain text export.",
    schema: driveExportAsSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'drive_get_comment',
    service: 'drive',
    action: 'commentsGet',
    description: "Get a specific Drive file comment by ID, including replies when returned by the Drive API.",
    schema: driveCommentGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Comment retrieved successfully." },
  },
  {
    name: 'drive_get_comments',
    service: 'drive',
    action: 'commentsList',
    description: "List comments on a Drive file. Returns comment id, content, author, createdTime, modifiedTime, resolved status, and replies count.",
    schema: driveCommentsListSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'drive_get_file',
    service: 'drive',
    action: 'fileGet',
    description: "Get detailed metadata for a Drive file by ID. Returns id, name, mimeType, url, size, created, updated, starred, trashed, owner, parents.",
    schema: fileGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "File metadata retrieved successfully." },
  },
  {
    name: 'drive_get_folder',
    service: 'drive',
    action: 'folderGet',
    description: "Get metadata for a Drive folder by ID. Returns id, name, url, created, updated, owner, parents.",
    schema: folderGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Folder metadata retrieved successfully." },
  },
  {
    name: 'drive_get_folder_path',
    service: 'drive',
    action: 'folderPath',
    description: "Get the full path from root to a file. Walks parent folders up to root Drive.",
    schema: driveFolderPathSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'drive_get_permissions',
    service: 'drive',
    action: 'fileGetPermissions',
    description: "Get sharing permissions for a Drive file. Returns sharing access level, permission level, owner, editors, and viewers.",
    schema: fileGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'drive_get_reply',
    service: 'drive',
    action: 'repliesGet',
    description: "Get a specific reply on a Drive file comment.",
    schema: driveReplyGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Reply retrieved successfully." },
  },
  {
    name: 'drive_get_revision',
    service: 'drive',
    action: 'revisionsGet',
    description: "Get metadata for a specific Drive file revision.",
    schema: driveRevisionGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Revision retrieved successfully." },
  },
  {
    name: 'drive_get_shared_drive',
    service: 'drive',
    action: 'sharedDrivesGet',
    description: "Get metadata and capabilities for a specific shared drive.",
    schema: driveSharedDriveGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Shared drive retrieved successfully." },
  },
  {
    name: 'drive_get_start_page_token',
    service: 'drive',
    action: 'changesStartPageToken',
    description: "Get a Drive changes start page token for My Drive or a shared drive.",
    schema: driveChangesStartPageTokenSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Start page token retrieved successfully." },
  },
  {
    name: 'drive_list_changes',
    service: 'drive',
    action: 'changesList',
    description: "List Drive changes from a start or next page token. Does not create watch channels.",
    schema: driveChangesListSchema,
    batchEligible: true,
    group: 'list',
    formatter: { kind: 'text', summary: "Drive changes retrieved successfully." },
  },
  {
    name: 'drive_list_files',
    service: 'drive',
    action: 'fileList',
    description: "List files in Drive. Optionally filter by folderId. Returns file name, id, mimeType, url, size, last updated, owner. Paginate with pageToken.",
    schema: fileListSchema,
    batchEligible: true,
    group: 'list',
    formatter: {
      kind: 'list',
      formatMcp: (result) => formatList(result, {
        itemsKey: 'items',
        noun: 'file',
        itemSummary: (item: unknown) => {
          const r = item as Record<string, unknown>
          return String(r.title ?? r.name ?? r.id ?? r.summary ?? JSON.stringify(r).slice(0, 120))
        },
      }),
    },
  },
  {
    name: 'drive_list_folders',
    service: 'drive',
    action: 'folderList',
    actions: ['folderList', 'folderListRoot'],
    resolveAction: (args) => (args.folderId ? 'folderList' : 'folderListRoot'),
    description: "List contents of a Drive folder (subfolders and files). If no folderId, lists root folder.",
    schema: folderListSchema,
    batchEligible: true,
    group: 'list',
    formatter: { kind: 'text' },
  },
  {
    name: 'drive_list_replies',
    service: 'drive',
    action: 'repliesList',
    description: "List replies on a Drive file comment.",
    schema: driveRepliesListSchema,
    batchEligible: true,
    group: 'list',
    formatter: { kind: 'text', summary: "Replies retrieved successfully." },
  },
  {
    name: 'drive_list_revisions',
    service: 'drive',
    action: 'revisionsList',
    description: "List Drive file revisions with metadata such as modified time, size, and keepForever when available.",
    schema: driveRevisionsListSchema,
    batchEligible: true,
    group: 'list',
    formatter: { kind: 'text', summary: "Revisions retrieved successfully." },
  },
  {
    name: 'drive_list_shared_drives',
    service: 'drive',
    action: 'sharedDrivesList',
    description: "List shared drives visible to the deploying user.",
    schema: driveSharedDrivesListSchema,
    batchEligible: true,
    group: 'list',
    formatter: { kind: 'text', summary: "Shared drives retrieved successfully." },
  },
  {
    name: 'drive_move_file',
    service: 'drive',
    action: 'fileMove',
    description: "Move a file to a different folder.",
    schema: fileMoveSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "File moved successfully." },
  },
  {
    name: 'drive_read_file',
    service: 'drive',
    action: 'fileExport',
    description: "Read the content of a Drive file as text. Works for Docs, Sheets, plain text, markdown, JSON, etc. Content is truncated at 500KB.",
    schema: fileExportSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'drive_remove_editor',
    service: 'drive',
    action: 'fileRemoveEditor',
    description: "Remove an editor from a file by email address.",
    schema: fileRemoveEditorSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Editor removed successfully." },
  },
  {
    name: 'drive_remove_parent',
    service: 'drive',
    action: 'fileRemoveParent',
    description: "Remove a file from a specific parent folder.",
    schema: driveRemoveParentSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "File removed from folder." },
  },
  {
    name: 'drive_remove_viewer',
    service: 'drive',
    action: 'fileRemoveViewer',
    description: "Remove a viewer from a file by email address.",
    schema: fileRemoveViewerSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Viewer removed successfully." },
  },
  {
    name: 'drive_search_files',
    service: 'drive',
    action: 'fileSearch',
    description: "Search Drive files with Google Drive query syntax. Supports: mimeType, name, modifiedTime, fullText, parents, starred, trashed. Example: \"name contains 'report'\" or \"mimeType = 'application/pdf'\".",
    schema: fileSearchSchema,
    batchEligible: true,
    group: 'list',
    formatter: {
      kind: 'list',
      formatMcp: (result) => formatList(result, {
        itemsKey: 'items',
        noun: 'result',
        itemSummary: (item: unknown) => {
          const r = item as Record<string, unknown>
          return String(r.title ?? r.name ?? r.id ?? r.summary ?? JSON.stringify(r).slice(0, 120))
        },
      }),
    },
  },
  {
    name: 'drive_set_sharing',
    service: 'drive',
    action: 'fileSetSharing',
    description: "Set sharing access and permission level for a file. Access: ANYONE, ANYONE_WITH_LINK, DOMAIN, DOMAIN_WITH_LINK, PRIVATE. Permission: VIEW, EDIT, COMMENT.",
    schema: fileSetSharingSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Sharing settings updated successfully." },
  },
  {
    name: 'drive_trash_file',
    service: 'drive',
    action: 'fileTrash',
    description: "Move a file to trash. Can be restored with drive_untrash_file.",
    schema: fileTrashSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "File moved to trash." },
  },
  {
    name: 'drive_untrash_file',
    service: 'drive',
    action: 'fileUntrash',
    description: "Restore a file from trash.",
    schema: fileUntrashSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "File restored from trash." },
  },
  {
    name: 'drive_update_comment',
    service: 'drive',
    action: 'commentsUpdate',
    description: "Update a Drive file comment content and/or resolved state.",
    schema: driveCommentUpdateSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Comment updated successfully." },
  },
  {
    name: 'drive_update_content',
    service: 'drive',
    action: 'fileUpdateContent',
    description: "Overwrite a file's content with new text. This replaces the entire file content.",
    schema: fileUpdateContentSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Content updated successfully." },
  },
  {
    name: 'drive_update_metadata',
    service: 'drive',
    action: 'fileUpdateMeta',
    description: "Update a file's name and/or description.",
    schema: fileUpdateMetaSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Metadata updated successfully." },
  },
  {
    name: 'drive_update_reply',
    service: 'drive',
    action: 'repliesUpdate',
    description: "Update the content of a Drive file comment reply.",
    schema: driveReplyUpdateSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Reply updated successfully." },
  },
  {
    name: 'drive_update_revision',
    service: 'drive',
    action: 'revisionsUpdate',
    description: "Update Drive revision metadata such as keepForever where the Drive API supports it.",
    schema: driveRevisionUpdateSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Revision updated successfully." },
  },
]
