import { formatList } from '../../response.js'
import {
  formsAddItemSchema,
  formsBatchSchema,
  formsCreateFormSchema,
  formsDeleteAllResponsesSchema,
  formsDeleteItemSchema,
  formsDeleteResponseSchema,
  formsGetFormSchema,
  formsGetResponseSchema,
  formsListItemsSchema,
  formsListResponsesSchema,
  formsMoveItemSchema,
  formsRemoveResponseDestinationSchema,
  formsSetAcceptingResponsesSchema,
  formsSetResponseDestinationSchema,
  formsUpdateFormSchema,
  formsUpdateItemSchema,
} from '../../schemas.js'
import type { ToolSpec } from '../types.js'

/** Forms service catalog — 16 tools. */
export const formsTools: ToolSpec[] = [
  {
    name: 'forms_create_form',
    service: 'forms',
    action: 'formCreate',
    description: 'Create a new Google Form with an optional description and initial publish state.',
    schema: formsCreateFormSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: 'Form created.' },
  },
  {
    name: 'forms_get_form',
    service: 'forms',
    action: 'formGet',
    description: 'Get Google Form metadata, settings, item summary, and response destination information.',
    schema: formsGetFormSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: 'Form retrieved.' },
  },
  {
    name: 'forms_update_form',
    service: 'forms',
    action: 'formUpdate',
    description: 'Update Google Form title, description, confirmation and response settings supported by FormsApp.',
    schema: formsUpdateFormSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: 'Form updated.' },
  },
  {
    name: 'forms_set_accepting_responses',
    service: 'forms',
    action: 'formSetAcceptingResponses',
    description: 'Open or close a Google Form for responses, optionally setting the custom closed-form message.',
    schema: formsSetAcceptingResponsesSchema,
    batchEligible: true,
    group: 'settings',
    formatter: { kind: 'text', summary: 'Accepting-responses setting updated.' },
  },
  {
    name: 'forms_set_response_destination',
    service: 'forms',
    action: 'formSetDestination',
    description: 'Link a Google Form response destination to a Google Sheets spreadsheet.',
    schema: formsSetResponseDestinationSchema,
    batchEligible: true,
    group: 'settings',
    formatter: { kind: 'text', summary: 'Response destination set.' },
  },
  {
    name: 'forms_remove_response_destination',
    service: 'forms',
    action: 'formRemoveDestination',
    description: 'Unlink a Google Form from its current response destination.',
    schema: formsRemoveResponseDestinationSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: 'Response destination removed.' },
  },
  {
    name: 'forms_list_items',
    service: 'forms',
    action: 'itemsList',
    description: 'List items in a Google Form with concise metadata and supported item-specific fields.',
    schema: formsListItemsSchema,
    batchEligible: true,
    group: 'list',
    formatter: {
      kind: 'list',
      formatMcp: (result) => formatList(result, {
        itemsKey: 'items',
        noun: 'item',
        itemSummary: (item: unknown) => {
          const record = item as Record<string, unknown>
          return `${record.index}: ${record.title || '(untitled)'} [${record.type}] (${record.itemId})`
        },
        hint: 'Use forms_update_item, forms_move_item, or forms_delete_item with formId and itemId to manage items.',
      }),
    },
  },
  {
    name: 'forms_add_item',
    service: 'forms',
    action: 'itemAdd',
    description: 'Add a supported item type to a Google Form: text, paragraph, multiple choice, checkbox, list, scale, date, time, section header, or page break.',
    schema: formsAddItemSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: 'Form item added.' },
  },
  {
    name: 'forms_update_item',
    service: 'forms',
    action: 'itemUpdate',
    description: 'Update common Google Form item fields and supported item-specific fields such as choices or scale bounds.',
    schema: formsUpdateItemSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: 'Form item updated.' },
  },
  {
    name: 'forms_move_item',
    service: 'forms',
    action: 'itemMove',
    description: 'Move a Google Form item to a new zero-based index.',
    schema: formsMoveItemSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: 'Form item moved.' },
  },
  {
    name: 'forms_delete_item',
    service: 'forms',
    action: 'itemDelete',
    description: 'Delete a Google Form item by item ID. Requires confirmation.',
    schema: formsDeleteItemSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: 'Form item deleted.' },
  },
  {
    name: 'forms_list_responses',
    service: 'forms',
    action: 'responsesList',
    description: 'List recent Google Form responses with concise answer metadata. Response content is capped by the proxy.',
    schema: formsListResponsesSchema,
    batchEligible: true,
    group: 'list',
    formatter: {
      kind: 'list',
      formatMcp: (result) => formatList(result, {
        itemsKey: 'items',
        noun: 'response',
        itemSummary: (item: unknown) => {
          const response = item as Record<string, unknown>
          return `${response.timestamp || '(no timestamp)'} (${response.responseId}) answers=${response.answerCount}`
        },
        hint: 'Use forms_get_response with formId and responseId for one response.',
      }),
    },
  },
  {
    name: 'forms_get_response',
    service: 'forms',
    action: 'responseGet',
    description: 'Get one Google Form response by response ID.',
    schema: formsGetResponseSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: 'Response retrieved.' },
  },
  {
    name: 'forms_delete_response',
    service: 'forms',
    action: 'responseDelete',
    description: 'Delete one Google Form response from the form response store. Requires confirmation.',
    schema: formsDeleteResponseSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: 'Response deleted.' },
  },
  {
    name: 'forms_delete_all_responses',
    service: 'forms',
    action: 'responsesDeleteAll',
    description: 'Delete all responses from a Google Form response store. Requires confirmation.',
    schema: formsDeleteAllResponsesSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: 'All responses deleted.' },
  },
  {
    name: 'forms_batch',
    service: 'forms',
    action: 'batch',
    description: 'Execute multiple Google Forms operations in a single round-trip. Operations execute sequentially; errors are collected per-operation. Up to 20 operations.',
    schema: formsBatchSchema,
    batchEligible: false,
    isBatchTool: true,
    group: 'batch',
    cli: { paramsJsonOnly: true },
    formatter: { kind: 'text', summary: 'Forms batch completed.' },
  },
]

