import {
  sheetsAddSheetSchema,
  sheetsAppendRowsSchema,
  sheetsBatchGetSchema,
  sheetsBatchSchema,
  sheetsClearRangeSchema,
  sheetsConditionalFormatSchema,
  sheetsCopySheetSchema,
  sheetsCreateChartSchema,
  sheetsDataValidationSchema,
  sheetsDeleteRowsSchema,
  sheetsDeleteSheetSchema,
  sheetsFindTextSchema,
  sheetsFormatRangeSchema,
  sheetsFreezeRowsSchema,
  sheetsGetFormulasSchema,
  sheetsGetNotesSchema,
  sheetsInsertRowsSchema,
  sheetsListProtectionsSchema,
  sheetsMergeCellsSchema,
  sheetsProtectRangeSchema,
  sheetsProtectSheetSchema,
  sheetsRangeReadSchema,
  sheetsRangeWriteSchema,
  sheetsRemoveProtectionSchema,
  sheetsRenameSheetSchema,
  sheetsReplaceTextSchema,
  sheetsSetColumnWidthSchema,
  sheetsSetFormulaSchema,
  sheetsSetNoteSchema,
  sheetsSortRangeSchema,
  sheetsSpreadsheetCreateSchema,
  sheetsSpreadsheetGetSchema,
} from '../../schemas.js'
import type { ToolSpec } from '../types.js'

/** sheets service catalog — 33 tools. */
export const sheetsTools: ToolSpec[] = [
  {
    name: 'sheets_add_sheet',
    service: 'sheets',
    action: 'sheetAdd',
    description: "Add a new sheet (tab) to a spreadsheet.",
    schema: sheetsAddSheetSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Sheet added." },
  },
  {
    name: 'sheets_append_rows',
    service: 'sheets',
    action: 'rowsAppend',
    description: "Append rows to the end of a sheet. Values is a 2D array where each inner array is a row.",
    schema: sheetsAppendRowsSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Rows appended." },
  },
  {
    name: 'sheets_batch',
    service: 'sheets',
    action: 'batch',
    description: "Execute multiple operations in a single round-trip against one existing spreadsheet. Pass an ordered array of {action, params} objects. Actions are the same names used by individual tools (spreadsheetGet, sheetAdd, sheetDelete, sheetRename, sheetCopy, rangeRead, rangeWrite, rowsAppend, rangeClear, rangeGetFormulas, rangeGetNotes, valuesBatchGet, textFind, textReplace, rangeFormat, rangeMerge, rangeUnmerge, columnWidth, freezeRows, rangeSort, formulaSet, chartCreate, noteSet, conditionalFormatGet, dataValidationSet, protectionsList, rangeProtect, sheetProtect, protectionRemove, rowsInsert, rowsDelete). Operations execute sequentially; errors are collected and returned per-operation with partial-success metadata.",
    schema: sheetsBatchSchema,
    batchEligible: false,
    isBatchTool: true,
    cli: { paramsJsonOnly: true },
    group: 'batch',
    formatter: { kind: 'text' },
  },
  {
    name: 'sheets_batch_get',
    service: 'sheets',
    action: 'valuesBatchGet',
    description: "Read multiple ranges from a spreadsheet in a single API call via the Sheets Advanced Service. Returns a valueRanges array, each with range, majorDimension, and values. Params: spreadsheetId, ranges (array of A1 notation strings).",
    schema: sheetsBatchGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'sheets_clear_range',
    service: 'sheets',
    action: 'rangeClear',
    description: "Clear values from a range. If no range is specified, clears all data in the sheet.",
    schema: sheetsClearRangeSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Range cleared." },
  },
  {
    name: 'sheets_copy_sheet',
    service: 'sheets',
    action: 'sheetCopy',
    description: "Copy a sheet within the same spreadsheet or to a different spreadsheet.",
    schema: sheetsCopySheetSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Sheet copied." },
  },
  {
    name: 'sheets_create_chart',
    service: 'sheets',
    action: 'chartCreate',
    description: "Create a chart in a sheet from a data range. Supports AREA, BAR, COLUMN, COMBO, HISTOGRAM, LINE, PIE, SCATTER, TABLE, TIMELINE, and WATERFALL chart types.",
    schema: sheetsCreateChartSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text' },
  },
  {
    name: 'sheets_create_spreadsheet',
    service: 'sheets',
    action: 'spreadsheetCreate',
    description: "Create a new Google Sheets spreadsheet.",
    schema: sheetsSpreadsheetCreateSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Spreadsheet created." },
  },
  {
    name: 'sheets_delete_rows',
    service: 'sheets',
    action: 'rowsDelete',
    description: "Delete rows at the specified position. Existing rows below are shifted up.",
    schema: sheetsDeleteRowsSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Rows deleted." },
  },
  {
    name: 'sheets_delete_sheet',
    service: 'sheets',
    action: 'sheetDelete',
    description: "Delete a sheet (tab) from a spreadsheet. Cannot delete the only remaining sheet.",
    schema: sheetsDeleteSheetSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Sheet deleted." },
  },
  {
    name: 'sheets_find_text',
    service: 'sheets',
    action: 'textFind',
    description: "Find text in a spreadsheet, sheet, or A1 range using Apps Script TextFinder options such as case sensitivity, regex, formula text, and diacritic handling.",
    schema: sheetsFindTextSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text' },
  },
  {
    name: 'sheets_format_range',
    service: 'sheets',
    action: 'rangeFormat',
    description: "Apply formatting to a range. Supports background, font color/size/family/bold/italic/underline/strikethrough, alignment, number format, text wrap, and borders. Only specified properties are applied.",
    schema: sheetsFormatRangeSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Formatting applied." },
  },
  {
    name: 'sheets_freeze_rows',
    service: 'sheets',
    action: 'freezeRows',
    description: "Freeze a number of rows at the top of a sheet (header rows). Set 0 to unfreeze.",
    schema: sheetsFreezeRowsSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text' },
  },
  {
    name: 'sheets_get_conditional_formatting',
    service: 'sheets',
    action: 'conditionalFormatGet',
    description: "Read conditional format rules on a sheet. Returns serialized rule descriptions with ranges, boolean conditions, and gradient conditions.",
    schema: sheetsConditionalFormatSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Conditional formatting rules retrieved." },
  },
  {
    name: 'sheets_get_notes',
    service: 'sheets',
    action: 'rangeGetNotes',
    description: "Read notes from a Google Sheets range.",
    schema: sheetsGetNotesSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'sheets_get_spreadsheet',
    service: 'sheets',
    action: 'spreadsheetGet',
    description: "Get spreadsheet metadata including ID, name, URL, and list of sheets (tabs) with row/column counts.",
    schema: sheetsSpreadsheetGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Spreadsheet metadata retrieved." },
  },
  {
    name: 'sheets_insert_rows',
    service: 'sheets',
    action: 'rowsInsert',
    description: "Insert blank rows at the specified position. Existing rows are shifted down.",
    schema: sheetsInsertRowsSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Rows inserted." },
  },
  {
    name: 'sheets_list_protections',
    service: 'sheets',
    action: 'protectionsList',
    description: "List protected ranges and sheets. Returns current filtered indexes for follow-up removal with sheets_remove_protection.",
    schema: sheetsListProtectionsSchema,
    batchEligible: true,
    group: 'list',
    formatter: { kind: 'text', summary: "Protections retrieved." },
  },
  {
    name: 'sheets_merge_cells',
    service: 'sheets',
    action: 'rangeMerge',
    description: "Merge a range of cells into one cell. Content is preserved from the top-left cell.",
    schema: sheetsMergeCellsSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Cells merged." },
  },
  {
    name: 'sheets_protect_range',
    service: 'sheets',
    action: 'rangeProtect',
    description: "Create a protected range with optional description, warning-only mode, additional editors, and domain edit setting.",
    schema: sheetsProtectRangeSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Range protected." },
  },
  {
    name: 'sheets_protect_sheet',
    service: 'sheets',
    action: 'sheetProtect',
    description: "Protect a sheet with optional description, warning-only mode, unprotected ranges, additional editors, and domain edit setting.",
    schema: sheetsProtectSheetSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Sheet protected." },
  },
  {
    name: 'sheets_read_formulas',
    service: 'sheets',
    action: 'rangeGetFormulas',
    description: "Read formulas and display values alongside raw values from a Google Sheets range.",
    schema: sheetsGetFormulasSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'sheets_read_range',
    service: 'sheets',
    action: 'rangeRead',
    description: "Read values from a Google Sheets range. Returns a 2D array of cell values in the specified range.",
    schema: sheetsRangeReadSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'sheets_remove_protection',
    service: 'sheets',
    action: 'protectionRemove',
    description: "Remove a protected range or sheet selected by type plus optional sheetName, range, description, and filtered index. Requires confirm=true.",
    schema: sheetsRemoveProtectionSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Protection removed." },
  },
  {
    name: 'sheets_rename_sheet',
    service: 'sheets',
    action: 'sheetRename',
    description: "Rename a sheet (tab) in a spreadsheet.",
    schema: sheetsRenameSheetSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Sheet renamed." },
  },
  {
    name: 'sheets_replace_text',
    service: 'sheets',
    action: 'textReplace',
    description: "Find and replace text in a spreadsheet, sheet, or A1 range using Apps Script TextFinder. Replacement text is treated as plain text; use sheets_set_formula for formulas.",
    schema: sheetsReplaceTextSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text' },
  },
  {
    name: 'sheets_set_column_width',
    service: 'sheets',
    action: 'columnWidth',
    description: "Set the width of a column in pixels.",
    schema: sheetsSetColumnWidthSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Column width set." },
  },
  {
    name: 'sheets_set_data_validation',
    service: 'sheets',
    action: 'dataValidationSet',
    description: "Set data validation on a range. Supports VALUE_IN_LIST, NUMBER_BETWEEN, NUMBER_GREATER_THAN, TEXT_CONTAINS, DATE_BEFORE, CHECKBOX, CUSTOM_FORMULA, and more.",
    schema: sheetsDataValidationSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Data validation set." },
  },
  {
    name: 'sheets_set_formula',
    service: 'sheets',
    action: 'formulaSet',
    description: "Set a formula in a cell or range (e.g. \"=SUM(A1:A10)\", \"=IF(A1>0,\\\\\"yes\\\\\",\\\\\"no\\\\\")\").",
    schema: sheetsSetFormulaSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Formula set." },
  },
  {
    name: 'sheets_set_note',
    service: 'sheets',
    action: 'noteSet',
    description: "Add or clear a note in a cell or range. Use an empty string to clear notes.",
    schema: sheetsSetNoteSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Note updated." },
  },
  {
    name: 'sheets_sort_range',
    service: 'sheets',
    action: 'rangeSort',
    description: "Sort a range by a single column. Header rows outside the range are not sorted.",
    schema: sheetsSortRangeSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Range sorted." },
  },
  {
    name: 'sheets_unmerge_cells',
    service: 'sheets',
    action: 'rangeUnmerge',
    description: "Unmerge a range of cells back into individual cells.",
    schema: sheetsMergeCellsSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Cells unmerged." },
  },
  {
    name: 'sheets_write_range',
    service: 'sheets',
    action: 'rangeWrite',
    description: "Write values to a Google Sheets range. Values is a 2D array where each inner array is a row.",
    schema: sheetsRangeWriteSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Values written." },
  },
]
