import {
  slidesAddSlideSchema,
  slidesBackgroundSchema,
  slidesBatchSchema,
  slidesCreatePresentationSchema,
  slidesDeleteElementSchema,
  slidesElementAltTextSchema,
  slidesElementGeometrySchema,
  slidesElementGetSchema,
  slidesElementLinkSchema,
  slidesElementReorderSchema,
  slidesElementTransformSchema,
  slidesFormatTextSchema,
  slidesGetElementTextSchema,
  slidesInsertImageSchema,
  slidesInsertLineSchema,
  slidesInsertShapeSchema,
  slidesInsertTableSchema,
  slidesInsertTextBoxSchema,
  slidesMoveSlideSchema,
  slidesPresentationGetSchema,
  slidesReplaceAllTextSchema,
  slidesSlideIndexSchema,
  slidesSlideNotesSchema,
} from '../../schemas.js'
import type { ToolSpec } from '../types.js'

/** slides service catalog — 25 tools. */
export const slidesTools: ToolSpec[] = [
  {
    name: 'slides_add_slide',
    service: 'slides',
    action: 'slideAdd',
    description: "Add a new slide to a presentation. Optionally sets title and body text if the layout supports it.",
    schema: slidesAddSlideSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Slide added." },
  },
  {
    name: 'slides_batch',
    service: 'slides',
    action: 'batch',
    description: "Execute multiple operations in a single round-trip against one existing presentation. Pass an ordered array of {action, params} objects. Actions are the same names used by individual tools (presentationGet, slideAdd, slideDelete, slideDuplicate, slideMove, textBoxInsert, imageInsert, shapeInsert, tableInsert, lineInsert, slideElementsList, elementDelete, elementGet, elementGetText, elementFormatText, elementGeometryUpdate, elementTransformUpdate, elementAltTextSet, elementLinkSet, elementReorder, slideNotes, textReplaceAll, slideBackground). Operations execute sequentially; errors are collected per-operation with partial-success metadata. Requires presentationId.",
    schema: slidesBatchSchema,
    batchEligible: false,
    isBatchTool: true,
    cli: { paramsJsonOnly: true },
    group: 'batch',
    formatter: { kind: 'text' },
  },
  {
    name: 'slides_create_presentation',
    service: 'slides',
    action: 'presentationCreate',
    description: "Create a new Google Slides presentation.",
    schema: slidesCreatePresentationSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Presentation created." },
  },
  {
    name: 'slides_delete_element',
    service: 'slides',
    action: 'elementDelete',
    description: "Delete a page element from a slide by its objectId. Get objectIds from slides_get_slide_elements.",
    schema: slidesDeleteElementSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text' },
  },
  {
    name: 'slides_delete_slide',
    service: 'slides',
    action: 'slideDelete',
    description: "Delete a slide by index (0-based).",
    schema: slidesSlideIndexSchema,
    batchEligible: true,
    group: 'manage',
    formatter: { kind: 'text', summary: "Slide deleted." },
  },
  {
    name: 'slides_duplicate_slide',
    service: 'slides',
    action: 'slideDuplicate',
    description: "Duplicate a slide by index (0-based). Inserts the copy after the original.",
    schema: slidesSlideIndexSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Slide duplicated." },
  },
  {
    name: 'slides_format_text',
    service: 'slides',
    action: 'elementFormatText',
    description: "Format text within a slide element (shape/text box). Finds all occurrences of findText in the element and applies the specified formatting.",
    schema: slidesFormatTextSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text' },
  },
  {
    name: 'slides_get_element',
    service: 'slides',
    action: 'elementGet',
    description: "Get one slide page element with geometry, rotation, alt text, and link metadata.",
    schema: slidesElementGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Element retrieved." },
  },
  {
    name: 'slides_get_element_text',
    service: 'slides',
    action: 'elementGetText',
    description: "Read text from a specific shape/text element on a slide. Get objectIds from slides_get_slide_elements.",
    schema: slidesGetElementTextSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'slides_get_presentation',
    service: 'slides',
    action: 'presentationGet',
    description: "Get presentation metadata including ID, name, URL, and list of slides with indices and object IDs.",
    schema: slidesPresentationGetSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text', summary: "Presentation metadata retrieved." },
  },
  {
    name: 'slides_get_slide_elements',
    service: 'slides',
    action: 'slideElementsList',
    description: "List all page elements on a slide with their types, IDs, positions, dimensions, and full text content (no truncation).",
    schema: slidesSlideIndexSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'slides_get_slide_notes',
    service: 'slides',
    action: 'slideNotes',
    description: "Get or set speaker notes for a slide. If notes param is provided, sets notes. If omitted, returns current notes.",
    schema: slidesSlideNotesSchema,
    batchEligible: true,
    group: 'read',
    formatter: { kind: 'text' },
  },
  {
    name: 'slides_insert_image',
    service: 'slides',
    action: 'imageInsert',
    description: "Insert an image from a public URL onto a slide at the specified position and size.",
    schema: slidesInsertImageSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Image inserted." },
  },
  {
    name: 'slides_insert_line',
    service: 'slides',
    action: 'lineInsert',
    description: "Insert a line connector between two points on a slide. Supports STRAIGHT, BENT, and CURVED line categories with optional line type (SOLID, DOTTED, DASHED).",
    schema: slidesInsertLineSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Line inserted." },
  },
  {
    name: 'slides_insert_shape',
    service: 'slides',
    action: 'shapeInsert',
    description: "Insert a shape on a slide. Supports RECTANGLE, ROUND_RECTANGLE, ELLIPSE, TRIANGLE, ARROW_RIGHT, ARROW_LEFT, STAR_5, HEXAGON, CLOUD, FLOW_CHART_PROCESS, FLOW_CHART_DECISION, WAVE, CHEVRON, PENTAGON, TRAPEZOID.",
    schema: slidesInsertShapeSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Shape inserted." },
  },
  {
    name: 'slides_insert_table',
    service: 'slides',
    action: 'tableInsert',
    description: "Insert a table on a slide with the given 2D array of values.",
    schema: slidesInsertTableSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Table inserted." },
  },
  {
    name: 'slides_insert_text_box',
    service: 'slides',
    action: 'textBoxInsert',
    description: "Insert a text box on a slide. Auto-positions below existing elements by default. Set autoPosition:false or provide coordinates to override.",
    schema: slidesInsertTextBoxSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Text box inserted." },
  },
  {
    name: 'slides_move_slide',
    service: 'slides',
    action: 'slideMove',
    description: "Move a slide to a different position by index (0-based).",
    schema: slidesMoveSlideSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Slide moved." },
  },
  {
    name: 'slides_reorder_element',
    service: 'slides',
    action: 'elementReorder',
    description: "Change element z-order: bring forward/front or send backward/back.",
    schema: slidesElementReorderSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Element z-order updated." },
  },
  {
    name: 'slides_replace_all_text',
    service: 'slides',
    action: 'textReplaceAll',
    description: "Find and replace text across all slides in a presentation.",
    schema: slidesReplaceAllTextSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text' },
  },
  {
    name: 'slides_set_element_alt_text',
    service: 'slides',
    action: 'elementAltTextSet',
    description: "Set or clear accessibility title and description on a slide element.",
    schema: slidesElementAltTextSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Element alt text updated." },
  },
  {
    name: 'slides_set_element_link',
    service: 'slides',
    action: 'elementLinkSet',
    description: "Set an element link to an HTTPS URL, link to another slide, or clear the link.",
    schema: slidesElementLinkSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Element link updated." },
  },
  {
    name: 'slides_set_slide_background',
    service: 'slides',
    action: 'slideBackground',
    description: "Set the background color of a slide using a solid fill color.",
    schema: slidesBackgroundSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Slide background set." },
  },
  {
    name: 'slides_update_element_geometry',
    service: 'slides',
    action: 'elementGeometryUpdate',
    description: "Update a slide element position, size, and/or rotation in points/degrees.",
    schema: slidesElementGeometrySchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Element geometry updated." },
  },
  {
    name: 'slides_update_element_transform',
    service: 'slides',
    action: 'elementTransformUpdate',
    description: "Update a slide element affine transform using the constrained Slides API transform fields.",
    schema: slidesElementTransformSchema,
    batchEligible: true,
    group: 'write',
    formatter: { kind: 'text', summary: "Element transform updated." },
  },
]
