/** Sheets smoke suite on a run-created spreadsheet (trashed via drive in cleanup). */
export const suite = {
  service: 'sheets',
  steps: [
    { tool: 'sheets_create_spreadsheet', params: (c) => ({ name: `${c.prefix}-sheet` }), save: { key: 'sheet', pick: 'data.spreadsheet.id' } },
    { tool: 'sheets_get_spreadsheet', params: (c) => ({ spreadsheetId: c.sheet }) },
    { tool: 'sheets_write_range', params: (c) => ({ spreadsheetId: c.sheet, range: 'A1:B3', values: [['name', 'value'], ['beta', 2], ['alpha', 1]] }) },
    { tool: 'sheets_read_range', params: (c) => ({ spreadsheetId: c.sheet, range: 'A1:B3' }) },
    { tool: 'sheets_append_rows', params: (c) => ({ spreadsheetId: c.sheet, values: [['gamma', 3]] }) },
    { tool: 'sheets_add_sheet', params: (c) => ({ spreadsheetId: c.sheet, sheetName: 'smoke-tab' }) },
    { tool: 'sheets_rename_sheet', params: (c) => ({ spreadsheetId: c.sheet, oldName: 'smoke-tab', newName: 'smoke-tab2' }) },
    { tool: 'sheets_copy_sheet', params: (c) => ({ spreadsheetId: c.sheet, sheetName: 'Sheet1', newName: 'smoke-copy' }) },
    { tool: 'sheets_freeze_rows', params: (c) => ({ spreadsheetId: c.sheet, numRows: 1 }) },
    { tool: 'sheets_set_column_width', params: (c) => ({ spreadsheetId: c.sheet, column: 1, width: 140 }) },
    { tool: 'sheets_merge_cells', params: (c) => ({ spreadsheetId: c.sheet, sheetName: 'smoke-tab2', range: 'A1:B1' }) },
    { tool: 'sheets_unmerge_cells', params: (c) => ({ spreadsheetId: c.sheet, sheetName: 'smoke-tab2', range: 'A1:B1' }) },
    { tool: 'sheets_set_formula', params: (c) => ({ spreadsheetId: c.sheet, range: 'C2', formula: '=SUM(B2:B4)' }) },
    { tool: 'sheets_read_formulas', params: (c) => ({ spreadsheetId: c.sheet, range: 'C2' }) },
    { tool: 'sheets_format_range', params: (c) => ({ spreadsheetId: c.sheet, range: 'A1:B1', bold: true, background: '#FFF2CC' }) },
    { tool: 'sheets_find_text', params: (c) => ({ spreadsheetId: c.sheet, findText: 'alpha', sheetName: 'Sheet1' }) },
    { tool: 'sheets_replace_text', params: (c) => ({ spreadsheetId: c.sheet, findText: 'gamma', replaceText: 'delta', sheetName: 'Sheet1' }) },
    { tool: 'sheets_set_note', params: (c) => ({ spreadsheetId: c.sheet, range: 'A1', note: 'smoke note' }) },
    { tool: 'sheets_get_notes', params: (c) => ({ spreadsheetId: c.sheet, range: 'A1' }) },
    { tool: 'sheets_sort_range', params: (c) => ({ spreadsheetId: c.sheet, range: 'A2:B4', sortColumn: 1 }) },
    { tool: 'sheets_insert_rows', params: (c) => ({ spreadsheetId: c.sheet, startPosition: 2 }) },
    { tool: 'sheets_delete_rows', params: (c) => ({ spreadsheetId: c.sheet, startPosition: 2 }), gated: true },
    { tool: 'sheets_set_data_validation', params: (c) => ({ spreadsheetId: c.sheet, sheetName: 'smoke-tab2', range: 'B1:B3', validationType: 'CHECKBOX' }) },
    { tool: 'sheets_get_conditional_formatting', params: (c) => ({ spreadsheetId: c.sheet }) },
    { tool: 'sheets_create_chart', params: (c) => ({ spreadsheetId: c.sheet, range: 'A1:B3', chartType: 'COLUMN', title: 'smoke chart' }) },
    { tool: 'sheets_protect_range', params: (c) => ({ spreadsheetId: c.sheet, range: 'A1:B1', description: `${c.prefix}-prot` }) },
    { tool: 'sheets_protect_sheet', params: (c) => ({ spreadsheetId: c.sheet, sheetName: 'smoke-tab2', description: `${c.prefix}-sheet-prot`, warningOnly: true }) },
    { tool: 'sheets_list_protections', params: (c) => ({ spreadsheetId: c.sheet }) },
    { tool: 'sheets_remove_protection', params: (c) => ({ spreadsheetId: c.sheet, type: 'RANGE', description: `${c.prefix}-prot` }), gated: true },
    { tool: 'sheets_remove_protection', params: (c) => ({ spreadsheetId: c.sheet, type: 'SHEET', description: `${c.prefix}-sheet-prot` }), gated: true },
    { tool: 'sheets_clear_range', params: (c) => ({ spreadsheetId: c.sheet, sheetName: 'smoke-copy', range: 'A1:B4' }), gated: true },
    { tool: 'sheets_batch_get', params: (c) => ({ spreadsheetId: c.sheet, ranges: ['Sheet1!A1:B2'] }) },
    { tool: 'sheets_delete_sheet', params: (c) => ({ spreadsheetId: c.sheet, sheetName: 'smoke-copy' }), gated: true },
    { tool: 'sheets_batch', params: (c) => ({ spreadsheetId: c.sheet, operations: [
      { action: 'spreadsheetGet', params: {} },
      { action: 'sheetDelete', params: { sheetName: 'smoke-tab2', confirm: true } },
    ] }), gated: true },
  ],
  cleanup: [
    { tool: 'drive_delete_file', params: (c) => ({ fileId: c.sheet }), gated: true, skip: (c) => (c.sheet ? null : 'no spreadsheet created') },
  ],
  verify: [
    { tool: 'drive_search_files', params: (c) => ({ query: `name contains '${c.prefix}-sheet' and trashed=false` }),
      leftovers: (body) => (Array.isArray(body.data) ? body.data.length : (body.data?.files ?? []).length) },
  ],
}
