#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

SERVICES=("drive" "gmail" "calendar" "sheets" "slides" "docs" "tasks" "forms")
DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=1
fi

banner() { echo -e "${BLUE}=== $1${NC}"; }
success() { echo -e "${GREEN}✓ $1${NC}"; }
warn() { echo -e "${YELLOW}⚠ $1${NC}"; }

ensure_bootstrap_secret() {
  local dir="$1"
  local file="$dir/BootstrapSecret.gs"
  if [ -f "$file" ]; then
    return 0
  fi
  local secret
  secret=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64url'))")
  cat > "$file" << EOF
// Generated by scripts/setup.sh. Do not commit this file.
const BOOTSTRAP_SETUP_SECRET = '$secret'
EOF
}

read_bootstrap_secret() {
  local file="$1/BootstrapSecret.gs"
  grep -o "BOOTSTRAP_SETUP_SECRET = '[^']*'" "$file" | sed "s/.*'\([^']*\)'/\1/"
}

service_title() {
  case "$1" in
    drive)    echo "Google Workspace Proxy - Drive" ;;
    gmail)    echo "Google Workspace Proxy - Gmail" ;;
    calendar) echo "Google Workspace Proxy - Calendar" ;;
    sheets)   echo "Google Workspace Proxy - Sheets" ;;
    slides)   echo "Google Workspace Proxy - Slides" ;;
    docs)     echo "Google Workspace Proxy - Docs" ;;
    tasks)    echo "Google Workspace Proxy - Tasks" ;;
    forms)    echo "Google Workspace Proxy - Forms" ;;
    *)        echo "" ;;
  esac
}

write_clasp_config() {
  local dir="$1"
  local script_id="$2"
  cat > "$dir/.clasp.json" << EOF
{
  "scriptId": "$script_id",
  "rootDir": "",
  "scriptExtensions": [
    ".js",
    ".gs"
  ],
  "htmlExtensions": [
    ".html"
  ],
  "jsonExtensions": [
    ".json"
  ],
  "filePushOrder": [],
  "skipSubdirectories": false
}
EOF
}

find_existing_project_id() {
  local title="$1"
  { clasp list --json 2>/dev/null || printf "[]"; } | node -e '
let data = "";
process.stdin.on("data", c => data += c);
process.stdin.on("end", () => {
  try {
    const title = process.argv[1];
    const projects = JSON.parse(data);
    const match = Array.isArray(projects) ? projects.find(p => p.name === title) : null;
    const id = match ? (match.id || match.scriptId) : "";
    if (id) console.log(id);
  } catch (_) {}
});
' "$title"
}

env_file_has_service_token() {
  local svc="$1"
  local env_name
  env_name=$(echo "$svc" | tr '[:lower:]' '[:upper:]')
  [ -f "$ROOT/.env" ] && grep -Eq "^export GOOGLE_WORKSPACE_${env_name}_PROXY_TOKEN=" "$ROOT/.env"
}

extract_token() {
  RESPONSE="$1" node -e '
try {
  const response = JSON.parse(process.env.RESPONSE || "{}");
  const token = response && response.success === true && response.data ? response.data.token : "";
  if (typeof token === "string" && /^[A-Za-z0-9_-]{60,}$/.test(token)) console.log(token);
} catch (_) {}
'
}

extract_error_code() {
  RESPONSE="$1" node -e '
try {
  const response = JSON.parse(process.env.RESPONSE || "{}");
  if (response && response.error && response.error.code) console.log(response.error.code);
} catch (_) {}
'
}

extract_error_message() {
  RESPONSE="$1" node -e '
try {
  const response = JSON.parse(process.env.RESPONSE || "{}");
  if (response && response.error && response.error.message) console.log(response.error.message);
} catch (_) {}
'
}

bootstrap_request() {
  local url="$1"
  local setup_key="$2"
  local rotate="${3:-false}"
  curl -sL -X POST -H 'Content-Type: application/json' -d "{\"setupKey\":\"${setup_key}\",\"rotate\":${rotate}}" "$url" 2>/dev/null || echo '{"success":false,"error":{"code":"NETWORK_ERROR","message":"Bootstrap request failed"}}'
}

# ── Prerequisites ──
banner "Prerequisites"
if [ "$DRY_RUN" -eq 1 ]; then
  warn "Dry run enabled: no clasp projects, Apps Script files, or .env output will be changed."
fi
if [ "$DRY_RUN" -eq 0 ] && ! command -v clasp &>/dev/null; then
  echo "clasp is not installed. Install it: npm install -g @google/clasp"
  exit 1
fi
if ! command -v node &>/dev/null; then
  echo "Node.js is required. Install Node 20+ from https://nodejs.org"
  exit 1
fi
if ! command -v npm &>/dev/null; then
  echo "npm is required. Install Node.js 20+ with npm from https://nodejs.org"
  exit 1
fi
if ! command -v curl &>/dev/null; then
  echo "curl is required for token bootstrap. Install curl or run setup from a shell that provides it."
  exit 1
fi
if [ "$DRY_RUN" -eq 1 ]; then
  success "Node.js, npm, and curl found; clasp check skipped"
else
  success "clasp, Node.js, npm, and curl found"
fi

# ── clasp login ──
banner "clasp login"
if [ "$DRY_RUN" -eq 1 ]; then
  warn "Skipping clasp authentication check in dry run."
elif ! clasp list &>/dev/null 2>&1; then
  echo "Logging into Google... A browser will open."
  clasp login
fi
if [ "$DRY_RUN" -eq 1 ]; then
  success "clasp authentication check skipped"
else
  success "clasp authenticated"
fi

# ── Build ──
banner "Build"
cd "$ROOT"
if [ -f package-lock.json ]; then
  npm ci --silent
else
  npm install --silent
fi
npm run build
success "Build complete"

# ── Create Projects + Push ──
banner "Creating Apps Script projects (${#SERVICES[@]} total)"
for svc in "${SERVICES[@]}"; do
  dir="$ROOT/packages/$svc/apps-script"
  echo ""
  echo "→ $svc"

  # Check if already has clasp project
  if [ -f "$dir/.clasp.json" ]; then
    existing_id=$(grep -o '"scriptId"[[:space:]]*:[[:space:]]*"[^"]*"' "$dir/.clasp.json" 2>/dev/null | grep -o '"[^"]*"$' | tr -d '"' || true)
    if [ -n "$existing_id" ] && [ "$existing_id" != "YOUR_SCRIPT_ID" ]; then
      warn "$svc already has a clasp project ($existing_id). Skipping creation."
      if [ "$DRY_RUN" -eq 0 ]; then
        ensure_bootstrap_secret "$dir"
        cd "$dir" && clasp push --force
      fi
      continue
    fi
  fi

  cd "$dir"
  if [ "$DRY_RUN" -eq 0 ]; then
    ensure_bootstrap_secret "$dir"
  else
    warn "$svc: would generate BootstrapSecret.gs if missing."
  fi

  manifest_backup=""
  if [ -f "$dir/appsscript.json" ]; then
    manifest_backup=$(mktemp)
    cp "$dir/appsscript.json" "$manifest_backup"
  fi

  title="$(service_title "$svc")"

  if [ "$DRY_RUN" -eq 1 ]; then
    warn "$svc: would reuse existing project named '$title' if present, otherwise create it and preserve appsscript.json."
    if [ -n "$manifest_backup" ]; then rm -f "$manifest_backup"; fi
    continue
  fi

  existing_project_id="$(find_existing_project_id "$title")"
  if [ -n "$existing_project_id" ]; then
    warn "$svc: reusing existing Apps Script project '$title' ($existing_project_id)."
    write_clasp_config "$dir" "$existing_project_id"
  else
    if [ -n "$manifest_backup" ]; then
      mv "$dir/appsscript.json" "$manifest_backup"
    fi

    if ! clasp create --type standalone --title "$title"; then
      warn "Could not create $svc project. Check clasp login and the full clasp output above."
      if [ -n "$manifest_backup" ]; then mv "$manifest_backup" "$dir/appsscript.json"; fi
      continue
    fi
  fi

  if [ -n "$manifest_backup" ]; then
    mv "$manifest_backup" "$dir/appsscript.json"
  fi

  clasp push --force
  success "$svc: project created and code pushed"
done

# ── Deployment Guide ──
banner "Deployment"
echo ""
echo "Each service needs a manual Apps Script web app deployment. You'll need to do this ${#SERVICES[@]} times."
echo "Do not use clasp deploy for this step; create the web app deployment in the Apps Script editor so access settings are explicit."
echo "For each service below:"
echo "  1. Open the Apps Script editor URL for the service"
echo "  2. Click Deploy → New deployment"
echo "  3. Click Select type / gear icon → Web app"
echo "  4. Set Execute as: Me (USER_DEPLOYING)"
echo "  5. Set Who has access: Anyone"
echo "  6. Click Deploy and authorize scopes if prompted"
echo "  7. Copy the Web app URL ending in /exec"
echo ""
echo "Services to deploy:"
for svc in "${SERVICES[@]}"; do
  clasp_file="$ROOT/packages/$svc/apps-script/.clasp.json"
  script_id=$(grep -o '"scriptId"[[:space:]]*:[[:space:]]*"[^"]*"' "$clasp_file" 2>/dev/null | grep -o '"[^"]*"$' | tr -d '"' || true)
  if [ -n "$script_id" ] && [ "$script_id" != "YOUR_SCRIPT_ID" ]; then
    echo "  - $svc: https://script.google.com/d/$script_id/edit"
  else
    echo "  - $svc: create or configure packages/$svc/apps-script/.clasp.json first"
  fi
done
echo ""

# ── Token Bootstrap ──
banner "Bootstrap tokens"
echo ""
URL_SERVICES=()
URL_VALUES=()
BOOTSTRAPPED_COUNT=0
if [ "$DRY_RUN" -eq 1 ]; then
  warn "Skipping interactive token bootstrap and .env generation in dry run."
else
  echo "After manually deploying each service as a Web app, paste the /exec deployment URLs below."
  echo "Press Enter to skip a service and pause setup. You can rerun ./scripts/setup.sh after deploying it."
  echo ""

  for svc in "${SERVICES[@]}"; do
    read -r -p "Deployment URL for $svc: " url
    if [ -n "$url" ]; then
      URL_SERVICES+=("$svc")
      URL_VALUES+=("$url")
    fi
  done

  echo ""
  if [ "${#URL_SERVICES[@]}" -eq 0 ]; then
    warn "No deployment URLs provided; leaving .env unchanged."
  fi

  for i in "${!URL_SERVICES[@]}"; do
    svc="${URL_SERVICES[$i]}"
    url="${URL_VALUES[$i]}"
    dir="$ROOT/packages/$svc/apps-script"
    env_name=$(echo "$svc" | tr '[:lower:]' '[:upper:]')
    if env_file_has_service_token "$svc"; then
      warn "$svc: token already exists in .env. Skipping bootstrap."
      continue
    fi

    ensure_bootstrap_secret "$dir"
    setup_key=$(read_bootstrap_secret "$dir")
    echo "→ Bootstrapping $svc..."

    response=$(bootstrap_request "$url" "$setup_key" false)
    token=$(extract_token "$response")
    code=$(extract_error_code "$response")

    if [ -z "$token" ]; then
      if [ "$code" = "FORBIDDEN" ]; then
        warn "$svc: bootstrap was already completed but no token exists in .env."
        rotate_reply=""
        if [ -t 0 ]; then
          if read -r -p "Rotate the primary token for $svc using the local setup key? This invalidates the previous primary token. [y/N] " rotate_reply; then
            :
          fi
        else
          warn "$svc: non-interactive setup cannot rotate safely. Rerun setup interactively or call the rotation endpoint manually."
        fi
        case "$rotate_reply" in
          y|Y|yes|YES)
            response=$(bootstrap_request "$url" "$setup_key" true)
            token=$(extract_token "$response")
            ;;
        esac
      fi
    fi

    if [ -z "$token" ]; then
      msg=$(extract_error_message "$response")
      warn "Could not get token for $svc. ${msg:-Check the Apps Script deployment URL and BootstrapSecret.gs setup key.}"
      continue
    fi

    if [ "$BOOTSTRAPPED_COUNT" -eq 0 ]; then
      echo "" >> "$ROOT/.env"
      echo "# Generated on $(date)" >> "$ROOT/.env"
    fi

    cat >> "$ROOT/.env" << EOF
export GOOGLE_WORKSPACE_${env_name}_PROXY_URL="$url"
export GOOGLE_WORKSPACE_${env_name}_PROXY_TOKEN="$token"
EOF

    BOOTSTRAPPED_COUNT=$((BOOTSTRAPPED_COUNT + 1))
    success "$svc: token bootstrapped"
  done
fi

# ── Config output ──
banner "OpenCode Config"
echo ""
echo "Add these entries to your opencode.jsonc under \"mcp\":"
echo ""

for svc in "${SERVICES[@]}"; do
  env_name=$(echo "$svc" | tr '[:lower:]' '[:upper:]')
  name="google-${svc}"
  cat <<EOF
    "$name": {
      "type": "local",
      "command": ["npx", "tsx", "$ROOT/packages/$svc/src/index.ts"],
      "environment": {
        "GOOGLE_WORKSPACE_${env_name}_PROXY_URL": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_URL}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_READ_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_READ_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_WRITE_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_WRITE_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_SEND_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_SEND_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_SHARE_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_SHARE_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_DESTRUCTIVE_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_DESTRUCTIVE_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_ADMIN_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_ADMIN_TOKEN}"
      }
    },
EOF
  echo ""
done

# ── Skill ──
banner "Install skills"
echo ""
echo "  mkdir -p ~/.config/opencode/skills"
echo "  ln -sf \"$ROOT/skills/google-workspace\" ~/.config/opencode/skills/google-workspace"
echo "  ln -sf \"$ROOT/skills/workspace-lite-installer\" ~/.config/opencode/skills/workspace-lite-installer"
echo ""
if [ "$DRY_RUN" -eq 1 ]; then
  success "Dry run complete. No Apps Script projects, bootstrap secrets, or .env entries were changed."
elif [ "$BOOTSTRAPPED_COUNT" -eq 0 ]; then
  warn "Setup paused before token bootstrap. Complete the manual Apps Script web app deployments, then rerun ./scripts/setup.sh and paste /exec URLs to create .env entries."
  success "Apps Script projects were created or updated. MCP tools are not usable until tokens are bootstrapped."
elif [ "$BOOTSTRAPPED_COUNT" -lt "${#SERVICES[@]}" ]; then
  warn "Setup partially complete: bootstrapped $BOOTSTRAPPED_COUNT of ${#SERVICES[@]} services. Rerun ./scripts/setup.sh to finish skipped services."
  success "Restart OpenCode after configured services are added to opencode.jsonc."
else
  success "Setup complete. Restart OpenCode to use all 218 tools."
fi
