#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

SERVICES=("drive" "gmail" "calendar" "sheets" "slides" "docs" "tasks" "forms")
DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=1
fi

banner() { echo -e "${BLUE}=== $1${NC}"; }
success() { echo -e "${GREEN}✓ $1${NC}"; }
warn() { echo -e "${YELLOW}⚠ $1${NC}"; }

ensure_bootstrap_secret() {
  local dir="$1"
  local file="$dir/BootstrapSecret.gs"
  if [ -f "$file" ]; then
    return 0
  fi
  local secret
  secret=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64url'))")
  cat > "$file" << EOF
// Generated by scripts/setup.sh. Do not commit this file.
const BOOTSTRAP_SETUP_SECRET = '$secret'
EOF
}

read_bootstrap_secret() {
  local file="$1/BootstrapSecret.gs"
  grep -o "BOOTSTRAP_SETUP_SECRET = '[^']*'" "$file" | sed "s/.*'\([^']*\)'/\1/"
}

# ── Prerequisites ──
banner "Prerequisites"
if [ "$DRY_RUN" -eq 1 ]; then
  warn "Dry run enabled: no clasp projects, Apps Script files, or .env output will be changed."
fi
if [ "$DRY_RUN" -eq 0 ] && ! command -v clasp &>/dev/null; then
  echo "clasp is not installed. Install it: npm install -g @google/clasp"
  exit 1
fi
if ! command -v node &>/dev/null; then
  echo "Node.js is required. Install Node 20+ from https://nodejs.org"
  exit 1
fi
if [ "$DRY_RUN" -eq 1 ]; then
  success "Node.js found; clasp check skipped"
else
  success "clasp and Node.js found"
fi

# ── clasp login ──
banner "clasp login"
if [ "$DRY_RUN" -eq 1 ]; then
  warn "Skipping clasp authentication check in dry run."
elif ! clasp list &>/dev/null 2>&1; then
  echo "Logging into Google... A browser will open."
  clasp login
fi
if [ "$DRY_RUN" -eq 1 ]; then
  success "clasp authentication check skipped"
else
  success "clasp authenticated"
fi

# ── Build ──
banner "Build"
cd "$ROOT"
if [ -f package-lock.json ]; then
  npm ci --silent
else
  npm install --silent
fi
npm run build
success "Build complete"

# ── Create Projects + Push ──
banner "Creating Apps Script projects (${#SERVICES[@]} total)"
for svc in "${SERVICES[@]}"; do
  dir="$ROOT/packages/$svc/apps-script"
  echo ""
  echo "→ $svc"

  # Check if already has clasp project
  if [ -f "$dir/.clasp.json" ]; then
    existing_id=$(grep -o '"scriptId"[[:space:]]*:[[:space:]]*"[^"]*"' "$dir/.clasp.json" 2>/dev/null | grep -o '"[^"]*"$' | tr -d '"' || true)
    if [ -n "$existing_id" ] && [ "$existing_id" != "YOUR_SCRIPT_ID" ]; then
      warn "$svc already has a clasp project ($existing_id). Skipping creation."
      if [ "$DRY_RUN" -eq 0 ]; then
        ensure_bootstrap_secret "$dir"
        cd "$dir" && clasp push --force 2>&1 | tail -1
      fi
      continue
    fi
  fi

  cd "$dir"
  if [ "$DRY_RUN" -eq 0 ]; then
    ensure_bootstrap_secret "$dir"
  else
    warn "$svc: would generate BootstrapSecret.gs if missing."
  fi

  manifest_backup=""
  if [ -f "$dir/appsscript.json" ]; then
    manifest_backup=$(mktemp)
    cp "$dir/appsscript.json" "$manifest_backup"
  fi

  # Create project title
  title=""
  case "$svc" in
    drive)    title="Google Workspace Proxy - Drive" ;;
    gmail)    title="Google Workspace Proxy - Gmail" ;;
    calendar) title="Google Workspace Proxy - Calendar" ;;
    sheets)   title="Google Workspace Proxy - Sheets" ;;
    slides)   title="Google Workspace Proxy - Slides" ;;
    docs)     title="Google Workspace Proxy - Docs" ;;
    tasks)    title="Google Workspace Proxy - Tasks" ;;
    forms)    title="Google Workspace Proxy - Forms" ;;
  esac

  if [ "$DRY_RUN" -eq 1 ]; then
    warn "$svc: would create Apps Script project '$title' and preserve appsscript.json."
    if [ -n "$manifest_backup" ]; then rm -f "$manifest_backup"; fi
    continue
  fi

  if ! clasp create --type standalone --title "$title" 2>/dev/null; then
    warn "Could not create $svc project. Check clasp login."
    if [ -n "$manifest_backup" ]; then rm -f "$manifest_backup"; fi
    continue
  fi

  if [ -n "$manifest_backup" ]; then
    cp "$manifest_backup" "$dir/appsscript.json"
    rm -f "$manifest_backup"
  fi

  clasp push --force
  success "$svc: project created and code pushed"
done

# ── Deployment Guide ──
banner "Deployment"
echo ""
echo "Each service needs a manual Apps Script web app deployment. You'll need to do this ${#SERVICES[@]} times."
echo "Do not use clasp deploy for this step; create the web app deployment in the Apps Script editor so access settings are explicit."
echo "For each service below:"
echo "  1. Open the Apps Script editor URL for the service"
echo "  2. Click Deploy → New deployment"
echo "  3. Click Select type / gear icon → Web app"
echo "  4. Set Execute as: Me (USER_DEPLOYING)"
echo "  5. Set Who has access: Anyone"
echo "  6. Click Deploy and authorize scopes if prompted"
echo "  7. Copy the Web app URL ending in /exec"
echo ""
echo "Services to deploy:"
for svc in "${SERVICES[@]}"; do
  clasp_file="$ROOT/packages/$svc/apps-script/.clasp.json"
  script_id=$(grep -o '"scriptId"[[:space:]]*:[[:space:]]*"[^"]*"' "$clasp_file" 2>/dev/null | grep -o '"[^"]*"$' | tr -d '"' || true)
  if [ -n "$script_id" ] && [ "$script_id" != "YOUR_SCRIPT_ID" ]; then
    echo "  - $svc: https://script.google.com/d/$script_id/edit"
  else
    echo "  - $svc: create or configure packages/$svc/apps-script/.clasp.json first"
  fi
done
echo ""

# ── Token Bootstrap ──
banner "Bootstrap tokens"
echo ""
URL_SERVICES=()
URL_VALUES=()
BOOTSTRAPPED_COUNT=0
if [ "$DRY_RUN" -eq 1 ]; then
  warn "Skipping interactive token bootstrap and .env generation in dry run."
else
  echo "After manually deploying each service as a Web app, paste the /exec deployment URLs below."
  echo "Press Enter to skip a service and pause setup. You can rerun ./scripts/setup.sh after deploying it."
  echo ""

  for svc in "${SERVICES[@]}"; do
    read -r -p "Deployment URL for $svc: " url
    if [ -n "$url" ]; then
      URL_SERVICES+=("$svc")
      URL_VALUES+=("$url")
    fi
  done

  echo ""
  if [ "${#URL_SERVICES[@]}" -eq 0 ]; then
    warn "No deployment URLs provided; leaving .env unchanged."
  fi

  for i in "${!URL_SERVICES[@]}"; do
    svc="${URL_SERVICES[$i]}"
    url="${URL_VALUES[$i]}"
    dir="$ROOT/packages/$svc/apps-script"
    ensure_bootstrap_secret "$dir"
    setup_key=$(read_bootstrap_secret "$dir")
    echo "→ Bootstrapping $svc..."

    response=$(curl -sL "${url}?bootstrap=1&setupKey=${setup_key}" 2>/dev/null || echo '{"success":false}')
    token=$(echo "$response" | grep -o '"token"[[:space:]]*:[[:space:]]*"[^"]*"' | grep -o '"[^"]*"$' | tr -d '"')

    if [ -z "$token" ]; then
      warn "Could not get token for $svc. Already bootstrapped? The URL may have been bootstrapped before."
      continue
    fi

    if [ "$BOOTSTRAPPED_COUNT" -eq 0 ]; then
      echo "" >> "$ROOT/.env"
      echo "# Generated on $(date)" >> "$ROOT/.env"
    fi

    env_name=$(echo "$svc" | tr '[:lower:]' '[:upper:]')
    cat >> "$ROOT/.env" << EOF
export GOOGLE_WORKSPACE_${env_name}_PROXY_URL="$url"
export GOOGLE_WORKSPACE_${env_name}_PROXY_TOKEN="$token"
EOF

    BOOTSTRAPPED_COUNT=$((BOOTSTRAPPED_COUNT + 1))
    success "$svc: token bootstrapped"
  done
fi

# ── Config output ──
banner "OpenCode Config"
echo ""
echo "Add these entries to your opencode.jsonc under \"mcp\":"
echo ""

for svc in "${SERVICES[@]}"; do
  env_name=$(echo "$svc" | tr '[:lower:]' '[:upper:]')
  name="google-${svc}"
  cat <<EOF
    "$name": {
      "type": "local",
      "command": ["npx", "tsx", "$ROOT/packages/$svc/src/index.ts"],
      "environment": {
        "GOOGLE_WORKSPACE_${env_name}_PROXY_URL": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_URL}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_READ_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_READ_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_WRITE_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_WRITE_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_SEND_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_SEND_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_SHARE_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_SHARE_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_DESTRUCTIVE_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_DESTRUCTIVE_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_ADMIN_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_ADMIN_TOKEN}"
      }
    },
EOF
  echo ""
done

# ── Skill ──
banner "Install skills"
echo ""
echo "  mkdir -p ~/.config/opencode/skills"
echo "  ln -sf \"$ROOT/skills/google-workspace\" ~/.config/opencode/skills/google-workspace"
echo "  ln -sf \"$ROOT/skills/workspace-lite-installer\" ~/.config/opencode/skills/workspace-lite-installer"
echo ""
if [ "$DRY_RUN" -eq 1 ]; then
  success "Dry run complete. No Apps Script projects, bootstrap secrets, or .env entries were changed."
elif [ "$BOOTSTRAPPED_COUNT" -eq 0 ]; then
  warn "Setup paused before token bootstrap. Complete the manual Apps Script web app deployments, then rerun ./scripts/setup.sh and paste /exec URLs to create .env entries."
  success "Apps Script projects were created or updated. MCP tools are not usable until tokens are bootstrapped."
elif [ "$BOOTSTRAPPED_COUNT" -lt "${#SERVICES[@]}" ]; then
  warn "Setup partially complete: bootstrapped $BOOTSTRAPPED_COUNT of ${#SERVICES[@]} services. Rerun ./scripts/setup.sh to finish skipped services."
  success "Restart OpenCode after configured services are added to opencode.jsonc."
else
  success "Setup complete. Restart OpenCode to use all 218 tools."
fi
