#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

SERVICES=("drive" "gmail" "calendar" "sheets" "slides" "docs" "tasks")
DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=1
fi

banner() { echo -e "${BLUE}=== $1${NC}"; }
success() { echo -e "${GREEN}✓ $1${NC}"; }
warn() { echo -e "${YELLOW}⚠ $1${NC}"; }

ensure_bootstrap_secret() {
  local dir="$1"
  local file="$dir/BootstrapSecret.gs"
  if [ -f "$file" ]; then
    return 0
  fi
  local secret
  secret=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64url'))")
  cat > "$file" << EOF
// Generated by scripts/setup.sh. Do not commit this file.
const BOOTSTRAP_SETUP_SECRET = '$secret'
EOF
}

read_bootstrap_secret() {
  local file="$1/BootstrapSecret.gs"
  grep -o "BOOTSTRAP_SETUP_SECRET = '[^']*'" "$file" | sed "s/.*'\([^']*\)'/\1/"
}

# ── Prerequisites ──
banner "Prerequisites"
if [ "$DRY_RUN" -eq 1 ]; then
  warn "Dry run enabled: no clasp projects, Apps Script files, or .env output will be changed."
fi
if [ "$DRY_RUN" -eq 0 ] && ! command -v clasp &>/dev/null; then
  echo "clasp is not installed. Install it: npm install -g @google/clasp"
  exit 1
fi
if ! command -v node &>/dev/null; then
  echo "Node.js is required. Install Node 20+ from https://nodejs.org"
  exit 1
fi
success "clasp and Node.js found"

# ── clasp login ──
banner "clasp login"
if [ "$DRY_RUN" -eq 1 ]; then
  warn "Skipping clasp login in dry run."
elif ! clasp login --status &>/dev/null 2>&1; then
  echo "Logging into Google... A browser will open."
  clasp login
fi
success "clasp authenticated"

# ── Build ──
banner "Build"
cd "$ROOT"
if [ -f package-lock.json ]; then
  npm ci --silent
else
  npm install --silent
fi
npm run build
success "Build complete"

# ── Create Projects + Push ──
banner "Creating Apps Script projects (${#SERVICES[@]} total)"
for svc in "${SERVICES[@]}"; do
  dir="$ROOT/packages/$svc/apps-script"
  echo ""
  echo "→ $svc"

  # Check if already has clasp project
  if [ -f "$dir/.clasp.json" ]; then
    existing_id=$(grep -o '"scriptId"[[:space:]]*:[[:space:]]*"[^"]*"' "$dir/.clasp.json" 2>/dev/null | grep -o '"[^"]*"$' | tr -d '"' || true)
    if [ -n "$existing_id" ] && [ "$existing_id" != "YOUR_SCRIPT_ID" ]; then
      warn "$svc already has a clasp project ($existing_id). Skipping creation."
      if [ "$DRY_RUN" -eq 0 ]; then
        cd "$dir" && clasp push --force 2>&1 | tail -1
      fi
      continue
    fi
  fi

  cd "$dir"
  if [ "$DRY_RUN" -eq 0 ]; then
    ensure_bootstrap_secret "$dir"
  else
    warn "$svc: would generate BootstrapSecret.gs if missing."
  fi

  manifest_backup=""
  if [ -f "$dir/appsscript.json" ]; then
    manifest_backup=$(mktemp)
    cp "$dir/appsscript.json" "$manifest_backup"
  fi

  # Create project title
  title=""
  case "$svc" in
    drive)    title="Google Workspace Proxy - Drive" ;;
    gmail)    title="Google Workspace Proxy - Gmail" ;;
    calendar) title="Google Workspace Proxy - Calendar" ;;
    sheets)   title="Google Workspace Proxy - Sheets" ;;
    slides)   title="Google Workspace Proxy - Slides" ;;
    docs)     title="Google Workspace Proxy - Docs" ;;
    tasks)    title="Google Workspace Proxy - Tasks" ;;
  esac

  if [ "$DRY_RUN" -eq 1 ]; then
    warn "$svc: would create Apps Script project '$title' and preserve appsscript.json."
    if [ -n "$manifest_backup" ]; then rm -f "$manifest_backup"; fi
    continue
  fi

  if ! clasp create --type standalone --title "$title" 2>/dev/null; then
    warn "Could not create $svc project. Check clasp login."
    if [ -n "$manifest_backup" ]; then rm -f "$manifest_backup"; fi
    continue
  fi

  if [ -n "$manifest_backup" ]; then
    cp "$manifest_backup" "$dir/appsscript.json"
    rm -f "$manifest_backup"
  fi

  clasp push --force
  success "$svc: project created and code pushed"
done

# ── Deployment Guide ──
banner "Deployment"
echo ""
echo "Each service needs a web app deployment. You'll need to do this ${#SERVICES[@]} times."
echo "For each service below:"
echo "  1. Run: cd packages/<service>/apps-script && clasp open"
echo "  2. Deploy → New deployment → Type: Web app"
echo "  3. Execute as: Me (USER_DEPLOYING)"
echo "  4. Access: Anyone (anonymous)"
echo "  5. Copy the deployment URL"
echo ""
echo "Services to deploy:"
for svc in "${SERVICES[@]}"; do
  echo "  - $svc: cd packages/$svc/apps-script && clasp open"
done
echo ""

# ── Token Bootstrap ──
banner "Bootstrap tokens"
echo ""
if [ "$DRY_RUN" -eq 1 ]; then
  warn "Skipping interactive token bootstrap and .env generation in dry run."
  success "Dry run complete."
  exit 0
fi

echo "After deploying each service, paste the deployment URLs below."
echo "Press Enter to skip a service (can run again later)."
echo ""

URL_SERVICES=()
URL_VALUES=()
for svc in "${SERVICES[@]}"; do
  read -r -p "Deployment URL for $svc: " url
  if [ -n "$url" ]; then
    URL_SERVICES+=("$svc")
    URL_VALUES+=("$url")
  fi
done

echo ""
echo "# Generated on $(date)" > "$ROOT/.env"
echo "" >> "$ROOT/.env"

for i in "${!URL_SERVICES[@]}"; do
  svc="${URL_SERVICES[$i]}"
  url="${URL_VALUES[$i]}"
  dir="$ROOT/packages/$svc/apps-script"
  ensure_bootstrap_secret "$dir"
  setup_key=$(read_bootstrap_secret "$dir")
  echo "→ Bootstrapping $svc..."

  response=$(curl -sL "${url}?bootstrap=1&setupKey=${setup_key}" 2>/dev/null || echo '{"success":false}')
  token=$(echo "$response" | grep -o '"token"[[:space:]]*:[[:space:]]*"[^"]*"' | grep -o '"[^"]*"$' | tr -d '"')

  if [ -z "$token" ]; then
    warn "Could not get token for $svc. Already bootstrapped? The URL may have been bootstrapped before."
    continue
  fi

  env_name=$(echo "$svc" | tr '[:lower:]' '[:upper:]')
  cat >> "$ROOT/.env" << EOF
export GOOGLE_WORKSPACE_${env_name}_PROXY_URL="$url"
export GOOGLE_WORKSPACE_${env_name}_PROXY_TOKEN="$token"
EOF

  success "$svc: token bootstrapped"
done

# ── Config output ──
banner "OpenCode Config"
echo ""
echo "Add these entries to your opencode.jsonc under \"mcpServers\":"
echo ""

for svc in "${SERVICES[@]}"; do
  env_name=$(echo "$svc" | tr '[:lower:]' '[:upper:]')
  name="google-${svc}"
  cat <<EOF
    "$name": {
      "type": "local",
      "command": ["npx", "tsx", "$ROOT/packages/$svc/src/index.ts"],
      "environment": {
        "GOOGLE_WORKSPACE_${env_name}_PROXY_URL": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_URL}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_READ_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_READ_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_WRITE_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_WRITE_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_SEND_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_SEND_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_SHARE_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_SHARE_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_DESTRUCTIVE_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_DESTRUCTIVE_TOKEN}",
        "GOOGLE_WORKSPACE_${env_name}_PROXY_ADMIN_TOKEN": "{env:GOOGLE_WORKSPACE_${env_name}_PROXY_ADMIN_TOKEN}"
      }
    },
EOF
  echo ""
done

# ── Skill ──
banner "Install skill"
echo ""
echo "  ln -sf \"$ROOT/skills/google-workspace\" ~/.config/opencode/skills/google-workspace"
echo ""
success "Setup complete. Restart OpenCode to use all 153 tools."
